#ifndef STSENGINE_H
#define STSENGINE_H

enum STSE_Result
{
    STSE_RESULT_SUCCESS,
    STSE_RESULT_NOT_INITIALIZED,
    STSE_RESULT_ALREADY_INITIALIZED,
    STSE_RESULT_MAX_ALLOCATION_COUNT_REACHED
};

enum STSE_Result STSE_initialize();

void STSE_terminate();

#endif